using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace Weasel.EntityFrameworkCore.Tests.MigrationOperations.SampleGenerated;

/// <summary>
///     Stub DbContext generated by Weasel to host the Weasel-authored EF Core
///     migrations. It has no entities on purpose — the migrations are
///     attribute-only and carry their own operations.
///     <para>Register at startup with:</para>
///     <code>
///     services.AddDbContext&lt;WeaselSampleDbContext&gt;(o =&gt;
///         o.UseNpgsql(connectionString,
///             m =&gt; m.MigrationsHistoryTable("__EFMigrationsHistory", "efgen")));
///     </code>
///     <para>
///     or apply from the command line (reads the WEASEL_EF_CONNECTION
///     environment variable): <c>dotnet ef database update --context WeaselSampleDbContext</c>
///     </para>
/// </summary>
public partial class WeaselSampleDbContext : DbContext
{
    public WeaselSampleDbContext()
    {
    }

    public WeaselSampleDbContext(DbContextOptions<WeaselSampleDbContext> options) : base(options)
    {
    }

    /// <summary>
    ///     Connection string used when the context is constructed without
    ///     options (e.g. by the EF design-time tools). Set it at startup or
    ///     let the design-time factory read WEASEL_EF_CONNECTION.
    /// </summary>
    public static string? ConnectionString { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseNpgsql(
                ConnectionString
                ?? Environment.GetEnvironmentVariable("WEASEL_EF_CONNECTION")
                ?? throw new InvalidOperationException(
                    "Set WeaselSampleDbContext.ConnectionString or the WEASEL_EF_CONNECTION environment variable"),
                m => m.MigrationsHistoryTable("__EFMigrationsHistory", "efgen"));
        }

        // EF 9+ throws from Migrate() when the context model does not match the
        // last migration; harmless here (attribute-only migrations carry no
        // model snapshot) but suppressed defensively
        optionsBuilder.ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning));
    }
}

/// <summary>
///     Design-time factory so `dotnet ef database update --context WeaselSampleDbContext`, `dotnet ef migrations script` and
///     `dotnet ef migrations bundle` work without an application host.
/// </summary>
public partial class WeaselSampleDbContextFactory : IDesignTimeDbContextFactory<WeaselSampleDbContext>
{
    public WeaselSampleDbContext CreateDbContext(string[] args)
    {
        var builder = new DbContextOptionsBuilder<WeaselSampleDbContext>();
        builder.UseNpgsql(
            WeaselSampleDbContext.ConnectionString
            ?? Environment.GetEnvironmentVariable("WEASEL_EF_CONNECTION")
            ?? throw new InvalidOperationException(
                "Set the WEASEL_EF_CONNECTION environment variable for design-time use"),
            m => m.MigrationsHistoryTable("__EFMigrationsHistory", "efgen"));
        return new WeaselSampleDbContext(builder.Options);
    }
}
