version: '3'
services:
  postgresql:
    image: "postgres:15.3-alpine"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: marten_testing
      NAMEDATALEN: 100
  sqlserver:
      image: "mcr.microsoft.com/azure-sql-edge"
      ports:
          - "1433:1433"
      environment:
          - "ACCEPT_EULA=Y"
          - "SA_PASSWORD=P@55w0rd"
          - "MSSQL_PID=Developer"

