using Weasel.Core;

namespace Weasel.Postgresql;

/// <summary>
///     PostgreSQL implementation of <see cref="IDdlSyntaxStrategy" />.
///     <para>
///     Wired through <c>Tables.Table.WriteDropStatement</c> and the CREATE-TABLE
///     header in <c>WriteCreateStatement</c> as part of #270 step 8 (prototype).
///     Once <c>TableBase</c> lands in step 9 the shared CREATE algorithm will
///     consume the full strategy from <c>Weasel.Core</c> and these per-provider
///     <c>Table.WriteCreateStatement</c> overrides shrink to provider-specific
///     extras (partitioning, etc.).
///     </para>
/// </summary>
public sealed class PostgresqlDdlSyntax: IDdlSyntaxStrategy
{
    /// <summary>Process-wide singleton — strategy is stateless.</summary>
    public static readonly PostgresqlDdlSyntax Instance = new();

    private PostgresqlDdlSyntax() { }

    /// <inheritdoc />
    public string QuoteIdentifier(string name) => SchemaUtils.QuoteName(name, SchemaUtils.IdentifierUsage.General);

    /// <inheritdoc />
    /// <remarks>
    ///     PostgreSQL appends <c>CASCADE</c> so dependent views, foreign keys and
    ///     owned sequences are dropped atomically with the table — matches the
    ///     pre-strategy hand-written line in <c>Table.WriteDropStatement</c>.
    /// </remarks>
    public void WriteDropTable(TextWriter writer, DbObjectName identifier)
    {
        writer.WriteLine($"DROP TABLE IF EXISTS {identifier} CASCADE;");
    }

    /// <inheritdoc />
    public void WriteCreateTableHeader(TextWriter writer, DbObjectName identifier, CreationStyle style)
    {
        // When the caller already emitted a DROP (CreationStyle.DropThenCreate), the
        // header is the unguarded CREATE TABLE; otherwise we use IF NOT EXISTS.
        if (style == CreationStyle.DropThenCreate)
        {
            writer.WriteLine($"CREATE TABLE {identifier} (");
        }
        else
        {
            writer.WriteLine($"CREATE TABLE IF NOT EXISTS {identifier} (");
        }
    }

    /// <inheritdoc />
    /// <remarks>
    ///     PostgreSQL emits foreign keys as separate <c>ALTER TABLE ADD CONSTRAINT</c>
    ///     statements after the CREATE TABLE, not inline.
    /// </remarks>
    public bool InlineForeignKeyConstraints => false;

    /// <inheritdoc />
    /// <remarks>
    ///     Returns <c>SERIAL</c> — the historical PostgreSQL spelling. PG 10+
    ///     also supports <c>GENERATED BY DEFAULT AS IDENTITY</c>; that may
    ///     become a configurable variant of this strategy in a later step.
    /// </remarks>
    public string AutoIncrementToken => "SERIAL";

    /// <inheritdoc />
    public string StatementTerminator => ";";
}
