using Shouldly;
using Weasel.Core;
using Weasel.Oracle.Tables;
using Xunit;

namespace Weasel.Oracle.Tests.Tables;

/// <summary>
///     <c>GENERATED BY DEFAULT AS IDENTITY</c> is emitted as its own clause rather than as part of the
///     column type, so it is invisible in <c>ALL_TAB_COLUMNS.DATA_TYPE</c>. The reader never asked for
///     <c>IDENTITY_COLUMN</c>, so every column came back with <c>IsAutoNumber</c> false: an identity
///     column could not be told from an ordinary one, and adding or dropping identity on an existing
///     column reported no difference at all.
/// </summary>
public class detecting_identity_columns: IntegrationContext
{
    private const string SchemaName = "identity_cols";

    public detecting_identity_columns(): base(SchemaName)
    {
    }

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    private static Table Counters(bool autoIncrement)
    {
        var table = new Table($"{SchemaName}.counters");
        table.AddColumn<Guid>("id").AsPrimaryKey();

        var number = table.AddColumn<int>("number").NotNull();
        if (autoIncrement)
        {
            number.AutoIncrement();
        }

        return table;
    }

    [Fact]
    public async Task an_identity_column_matches_the_model_that_created_it()
    {
        // The regression: this delta was never empty, so every migration re-issued
        // ALTER TABLE ... MODIFY number NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
        // which Oracle rejects on a column that already is an identity.
        await ResetSchema();

        await CreateSchemaObjectInDatabase(Counters(autoIncrement: true));

        var delta = await Counters(autoIncrement: true).FindDeltaAsync(theConnection, Ct);

        delta.Columns.Different.ShouldBeEmpty();
        delta.Difference.ShouldBe(SchemaPatchDifference.None);
    }

    [Fact]
    public async Task the_migration_path_settles_on_an_identity_column()
    {
        await ResetSchema();

        (await Counters(autoIncrement: true).MigrateAsync(theConnection)).ShouldBeTrue();
        (await Counters(autoIncrement: true).MigrateAsync(theConnection)).ShouldBeFalse();
    }

    [Fact]
    public async Task a_plain_column_still_matches_a_plain_model()
    {
        // The negative control for the reader: IDENTITY_COLUMN is 'NO' here, and reading it must not
        // turn an ordinary column into an identity one.
        await ResetSchema();

        await CreateSchemaObjectInDatabase(Counters(autoIncrement: false));

        var delta = await Counters(autoIncrement: false).FindDeltaAsync(theConnection, Ct);

        delta.Columns.Different.ShouldBeEmpty();
        delta.Difference.ShouldBe(SchemaPatchDifference.None);
    }

    [Fact]
    public async Task adding_identity_to_an_existing_plain_column_is_now_a_difference()
    {
        // Before IsAutoNumber counted towards equality this reported None, so a model that started
        // declaring identity silently never got it.
        await ResetSchema();

        await CreateSchemaObjectInDatabase(Counters(autoIncrement: false));

        var delta = await Counters(autoIncrement: true).FindDeltaAsync(theConnection, Ct);

        delta.Columns.Different.ShouldNotBeEmpty();
    }

    [Fact]
    public async Task dropping_identity_from_an_existing_column_is_now_a_difference()
    {
        await ResetSchema();

        await CreateSchemaObjectInDatabase(Counters(autoIncrement: true));

        var delta = await Counters(autoIncrement: false).FindDeltaAsync(theConnection, Ct);

        delta.Columns.Different.ShouldNotBeEmpty();
    }
}
