using Shouldly;
using Weasel.Core;
using Weasel.Oracle.Tables;
using Xunit;

namespace Weasel.Oracle.Tests.Tables;

public class TableColumnTests
{
    [Fact]
    public void name_is_lowercased_and_trimmed()
    {
        var column = new TableColumn("  MyColumn  ", "VARCHAR2(100)");
        column.Name.ShouldBe("mycolumn");
    }

    [Fact]
    public void type_is_uppercased()
    {
        var column = new TableColumn("name", "varchar2(100)");
        column.Type.ShouldBe("VARCHAR2(100)");
    }

    /// <summary>
    ///     This asserted <c>first name</c> becoming <c>first_name</c> until weasel#458. The
    ///     expectation changed rather than the test being deleted, because the rewrite was real
    ///     and long-standing — it just was not anybody's decision. Only <c>TableColumn</c> did it,
    ///     so an index or foreign key over the same name still said <c>first name</c> and
    ///     referenced a column that did not exist.
    /// </summary>
    /// <remarks>
    ///     A space is a legal identifier character (weasel#448) and every provider quotes for shape
    ///     (weasel#447), so the caller's name is now the column's name.
    /// </remarks>
    [Fact]
    public void a_space_in_a_name_is_kept_rather_than_rewritten()
    {
        var column = new TableColumn("first name", "VARCHAR2(100)");
        column.Name.ShouldBe("first name");
    }

    [Fact]
    public void default_allows_nulls()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.AllowNulls.ShouldBeTrue();
    }

    [Fact]
    public void declaration_for_nullable_column()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.Declaration().ShouldBe("NULL");
    }

    [Fact]
    public void declaration_for_not_null_column()
    {
        var column = new TableColumn("name", "VARCHAR2(100)") { AllowNulls = false };
        column.Declaration().ShouldBe("NOT NULL");
    }

    [Fact]
    public void declaration_for_primary_key()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn<int>("id").AsPrimaryKey();

        table.Columns[0].Declaration().ShouldBe("NOT NULL");
    }

    [Fact]
    public void declaration_with_default_expression()
    {
        var column = new TableColumn("created_at", "DATE")
        {
            DefaultExpression = "SYSDATE"
        };
        column.Declaration().ShouldBe("DEFAULT SYSDATE NULL");
    }

    [Fact]
    public void declaration_with_auto_number()
    {
        var column = new TableColumn("id", "NUMBER(10)")
        {
            IsAutoNumber = true,
            AllowNulls = false
        };
        column.Declaration().ShouldBe("NOT NULL GENERATED BY DEFAULT AS IDENTITY");
    }

    [Fact]
    public void to_declaration()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.ToDeclaration().ShouldBe("name VARCHAR2(100) NULL");
    }

    [Fact]
    public void equality_based_on_name_and_type()
    {
        var column1 = new TableColumn("name", "VARCHAR2(100)");
        var column2 = new TableColumn("name", "VARCHAR2(100)");
        var column3 = new TableColumn("name", "NUMBER(10)");

        column1.Equals(column2).ShouldBeTrue();
        column1.Equals(column3).ShouldBeFalse();
    }

    [Theory]
    [InlineData("NUMERIC(13,4)", "NUMBER(13,4)")]
    [InlineData("DECIMAL(10,2)", "NUMBER(10,2)")]
    [InlineData("INTEGER", "NUMBER")]
    [InlineData("SMALLINT", "NUMBER")]
    [InlineData("REAL", "FLOAT(63)")]
    [InlineData("VARCHAR(50)", "VARCHAR2(50)")]
    [InlineData("CHARACTER(10)", "CHAR(10)")]
    [InlineData("NATIONAL CHARACTER VARYING(10)", "NVARCHAR2(10)")]
    [InlineData("VARCHAR2(100 CHAR)", "VARCHAR2(100)")]
    [InlineData("INTERVAL DAY TO SECOND", "INTERVAL DAY(2) TO SECOND(6)")]
    [InlineData("INTERVAL YEAR TO MONTH", "INTERVAL YEAR(2) TO MONTH")]
    public void a_declared_type_equals_the_type_oracle_stores_for_it(string declared, string stored)
    {
        new TableColumn("value", declared).Equals(new TableColumn("value", stored)).ShouldBeTrue();
    }

    [Theory]
    [InlineData("NUMERIC(13,4)", "VARCHAR2(13)")]
    [InlineData("INTERVAL DAY TO SECOND", "INTERVAL YEAR(2) TO MONTH")]
    [InlineData("VARCHAR2(100 CHAR)", "VARCHAR2(200 CHAR)")]
    public void a_different_type_is_still_different(string declared, string stored)
    {
        new TableColumn("value", declared).Equals(new TableColumn("value", stored)).ShouldBeFalse();
    }

    [Theory]
    [InlineData("CHARACTER VARYING(200)", "VARCHAR2(100)")]
    [InlineData("CHAR VARYING(200)", "VARCHAR2(100)")]
    [InlineData("NATIONAL CHARACTER VARYING(20)", "NVARCHAR2(10)")]
    [InlineData("NATIONAL CHAR VARYING(20)", "NVARCHAR2(10)")]
    [InlineData("NCHAR VARYING(20)", "NVARCHAR2(10)")]
    [InlineData("NATIONAL CHARACTER(20)", "NCHAR(10)")]
    [InlineData("NATIONAL CHAR(20)", "NCHAR(10)")]
    public void a_length_declared_through_a_multi_word_synonym_is_still_compared(string declared, string stored)
    {
        new TableColumn("value", declared).Equals(new TableColumn("value", stored)).ShouldBeFalse();
    }

    [Theory]
    [InlineData("NUMERIC(13,4)", "NUMBER(13,4)")]
    [InlineData("INTEGER", "NUMBER")]
    [InlineData("VARCHAR(50)", "VARCHAR2(50)")]
    [InlineData("CHARACTER VARYING(50)", "VARCHAR2(50)")]
    [InlineData("VARCHAR2(100 CHAR)", "VARCHAR2(100)")]
    [InlineData("INTERVAL DAY TO SECOND", "INTERVAL DAY(2) TO SECOND(6)")]
    public void columns_that_are_equal_hash_alike(string declared, string stored)
    {
        var expected = new TableColumn("value", declared);
        var actual = new TableColumn("value", stored);

        expected.Equals(actual).ShouldBeTrue();
        expected.GetHashCode().ShouldBe(actual.GetHashCode());
    }

    // Declared spellings for the two grids below: every synonym, sizes on both sides of the ones the
    // catalog reports, and lengths in bytes and in characters.
    private static readonly string[] DeclaredSpellings =
    [
        "NUMBER", "NUMBER(10)", "NUMBER(13,4)", "NUMERIC(13,4)", "DECIMAL", "DEC(10,2)", "INT", "INTEGER",
        "SMALLINT", "BIGINT", "BOOLEAN", "FLOAT", "FLOAT(126)", "REAL", "DOUBLE", "DOUBLE PRECISION",
        "BINARY_FLOAT", "BINARY_DOUBLE", "VARCHAR(100)", "VARCHAR(400)", "VARCHAR2(100)", "VARCHAR2(200)",
        "VARCHAR2(400)", "VARCHAR2(100 CHAR)", "VARCHAR2(400 CHAR)", "VARCHAR2(400 BYTE)",
        "CHARACTER VARYING(100)", "CHARACTER VARYING(400)", "CHAR VARYING(100)", "CHAR(10)", "CHAR(40)",
        "CHAR(10 CHAR)", "CHARACTER(10)", "CHARACTER(40)", "NCHAR(10)", "NCHAR(20)", "NCHAR(1000)",
        "NCHAR(2000)", "NATIONAL CHAR(10)", "NATIONAL CHAR(20)", "NVARCHAR2(100)", "NVARCHAR2(200)",
        "NVARCHAR2(2000)", "NVARCHAR2(4000)", "NCHAR VARYING(100)", "NCHAR VARYING(200)", "TEXT", "CLOB",
        "BLOB", "RAW(16)", "DATE", "TIMESTAMP", "TIMESTAMP(3)", "TIMESTAMP WITH TIME ZONE",
        "TIMESTAMP(3) WITH TIME ZONE", "TIMESTAMP WITH LOCAL TIME ZONE", "TIMESTAMP(3) WITH LOCAL TIME ZONE",
        "INTERVAL DAY TO SECOND", "INTERVAL DAY(3) TO SECOND(2)", "INTERVAL YEAR TO MONTH",
        "INTERVAL YEAR(4) TO MONTH"
    ];

    /// <summary>
    ///     Folding the declared spelling onto the stored one may only add matches. A declared type that
    ///     matched a catalog type the way the comparison used to work must still match it, or a column
    ///     that settled long ago starts migrating -- and changing the type of a populated column is
    ///     ORA-01439. <c>DOUBLE PRECISION</c> against <c>BINARY_DOUBLE</c> and <c>TIMESTAMP(n) WITH TIME
    ///     ZONE</c> against <c>TIMESTAMP</c> are the two pairs that would have broken.
    /// </summary>
    [Fact]
    public void nothing_that_matched_before_stops_matching()
    {
        // What the reader builds from ALL_TAB_COLUMNS.
        string[] stored =
        [
            "NUMBER", "NUMBER(10)", "NUMBER(13,4)", "FLOAT(126)", "FLOAT(63)", "BINARY_FLOAT", "BINARY_DOUBLE",
            "VARCHAR2(100)", "VARCHAR2(100 CHAR)", "VARCHAR2(400)", "CHAR(10)", "CHAR(10 CHAR)", "NCHAR(10)",
            "NVARCHAR2(100)", "CLOB", "BLOB", "RAW(16)", "DATE", "BOOLEAN", "TIMESTAMP",
            "TIMESTAMP WITH TIME ZONE", "TIMESTAMP WITH LOCAL TIME ZONE", "INTERVAL DAY(2) TO SECOND(6)",
            "INTERVAL DAY(3) TO SECOND(2)", "INTERVAL YEAR(2) TO MONTH"
        ];

        var stoppedMatching =
            from d in DeclaredSpellings
            from s in stored
            where matchedBefore(d, s) && !new TableColumn("value", d).Equals(new TableColumn("value", s))
            select $"{d} ~ {s}";

        stoppedMatching.ShouldBeEmpty();
    }

    /// <summary>
    ///     The same guarantee through the reader, which now reports a column sized in characters in
    ///     characters. Before, it reported <c>DATA_LENGTH</c>, the size in bytes, and a model stating that
    ///     matched. It still has to: <c>MODIFY</c>ing such a column to the byte size re-pads every stored
    ///     <c>CHAR</c> value, and for an <c>NVARCHAR2(2000)</c> it is ORA-00910 on every migration.
    /// </summary>
    [Fact]
    public void nothing_the_catalog_reported_that_matched_before_stops_matching()
    {
        // ALL_TAB_COLUMNS rows in an AL32UTF8 database with an AL16UTF16 national character set:
        // data_type, data_length, data_precision, data_scale, char_length, char_used.
        (string, int?, int?, int?, int?, string?)[] rows =
        [
            ("NUMBER", 22, null, null, 0, null), ("NUMBER", 22, 10, 0, 0, null), ("NUMBER", 22, 13, 4, 0, null),
            ("NUMBER", 22, null, 0, 0, null), ("FLOAT", 22, 126, null, 0, null), ("FLOAT", 22, 63, null, 0, null),
            ("BINARY_FLOAT", 4, null, null, 0, null), ("BINARY_DOUBLE", 8, null, null, 0, null),
            ("VARCHAR2", 100, null, null, 100, "B"), ("VARCHAR2", 400, null, null, 100, "C"),
            ("VARCHAR2", 400, null, null, 400, "B"), ("CHAR", 10, null, null, 10, "B"),
            ("CHAR", 40, null, null, 10, "C"), ("NCHAR", 20, null, null, 10, "C"),
            ("NCHAR", 2000, null, null, 1000, "C"), ("NVARCHAR2", 200, null, null, 100, "C"),
            ("NVARCHAR2", 4000, null, null, 2000, "C"), ("RAW", 16, null, null, 0, null),
            ("CLOB", 4000, null, null, 0, null), ("BLOB", 4000, null, null, 0, null),
            ("DATE", 7, null, null, 0, null), ("BOOLEAN", 1, null, null, 0, null),
            ("TIMESTAMP(6)", 11, null, 6, 0, null), ("TIMESTAMP(6) WITH TIME ZONE", 13, null, 6, 0, null),
            ("TIMESTAMP(6) WITH LOCAL TIME ZONE", 11, null, 6, 0, null),
            ("INTERVAL DAY(2) TO SECOND(6)", 11, 2, 6, 0, null), ("INTERVAL YEAR(2) TO MONTH", 5, 2, 0, 0, null)
        ];

        var matchedBeforeCount = 0;
        var stoppedMatching = new List<string>();

        foreach (var (dataType, dataLength, precision, scale, charLength, charUsed) in rows)
        {
            var before = typeAsReadBefore(dataType, dataLength, precision, scale);
            var now = Table.ReadColumn("value", dataType, dataLength, precision, scale, "Y", charLength, charUsed);

            foreach (var declared in DeclaredSpellings.Where(d => matchedBefore(d, before)))
            {
                matchedBeforeCount++;
                if (!new TableColumn("value", declared).Equals(now))
                {
                    stoppedMatching.Add($"{declared} ~ {now.Type} (read as {before} before)");
                }
            }
        }

        matchedBeforeCount.ShouldBeGreaterThan(50);
        stoppedMatching.ShouldBeEmpty();
    }

    // The type the reader built from a catalog row before it read CHAR_LENGTH: DATA_LENGTH for every
    // character and binary type.
    private static string typeAsReadBefore(string dataType, int? dataLength, int? precision, int? scale)
    {
        switch (dataType)
        {
            case "VARCHAR2" or "NVARCHAR2" or "CHAR" or "NCHAR" or "RAW":
                return dataLength.HasValue ? $"{dataType}({dataLength})" : dataType;
            case "NUMBER":
                if (precision.HasValue && scale is > 0) return $"NUMBER({precision},{scale})";
                return precision.HasValue ? $"NUMBER({precision})" : "NUMBER";
            case "FLOAT":
                return precision.HasValue ? $"FLOAT({precision})" : "FLOAT";
            default:
                return dataType.StartsWith("TIMESTAMP", StringComparison.Ordinal)
                    ? System.Text.RegularExpressions.Regex.Replace(dataType, @"\(\d+\)", "").Replace("  ", " ")
                    : dataType;
        }
    }

    // The type half of TableColumn.Equals as it was before the stored-name comparison.
    private static bool matchedBefore(string declared, string stored)
    {
        static string rawType(string type) => type.ToUpperInvariant().Split('(')[0].Trim();

        return !CharacterColumnLength.Differ(declared.ToUpperInvariant(), stored.ToUpperInvariant())
               && string.Equals(OracleProvider.Instance.ConvertSynonyms(rawType(declared)),
                   OracleProvider.Instance.ConvertSynonyms(rawType(stored)), StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void raw_type_extracts_type_without_size()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.RawType().ShouldBe("VARCHAR2");
    }

    [Fact]
    public void add_column_sql()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn("email", "VARCHAR2(200)");

        var column = table.Columns[0];
        column.AddColumnSql(table).ShouldBe("ALTER TABLE WEASEL.PEOPLE ADD email VARCHAR2(200) NULL");
    }

    [Fact]
    public void drop_column_sql()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn("email", "VARCHAR2(200)");

        var column = table.Columns[0];
        column.DropColumnSql(table).ShouldBe("ALTER TABLE WEASEL.PEOPLE DROP COLUMN email");
    }
}
