using Shouldly;
using Weasel.Oracle.Tables;
using Xunit;

namespace Weasel.Oracle.Tests.Tables;

public class TableColumnTests
{
    [Fact]
    public void name_is_lowercased_and_trimmed()
    {
        var column = new TableColumn("  MyColumn  ", "VARCHAR2(100)");
        column.Name.ShouldBe("mycolumn");
    }

    [Fact]
    public void type_is_uppercased()
    {
        var column = new TableColumn("name", "varchar2(100)");
        column.Type.ShouldBe("VARCHAR2(100)");
    }

    [Fact]
    public void spaces_in_name_are_replaced_with_underscores()
    {
        var column = new TableColumn("first name", "VARCHAR2(100)");
        column.Name.ShouldBe("first_name");
    }

    [Fact]
    public void default_allows_nulls()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.AllowNulls.ShouldBeTrue();
    }

    [Fact]
    public void declaration_for_nullable_column()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.Declaration().ShouldBe("NULL");
    }

    [Fact]
    public void declaration_for_not_null_column()
    {
        var column = new TableColumn("name", "VARCHAR2(100)") { AllowNulls = false };
        column.Declaration().ShouldBe("NOT NULL");
    }

    [Fact]
    public void declaration_for_primary_key()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn<int>("id").AsPrimaryKey();

        table.Columns[0].Declaration().ShouldBe("NOT NULL");
    }

    [Fact]
    public void declaration_with_default_expression()
    {
        var column = new TableColumn("created_at", "DATE")
        {
            DefaultExpression = "SYSDATE"
        };
        column.Declaration().ShouldBe("DEFAULT SYSDATE NULL");
    }

    [Fact]
    public void declaration_with_auto_number()
    {
        var column = new TableColumn("id", "NUMBER(10)")
        {
            IsAutoNumber = true,
            AllowNulls = false
        };
        column.Declaration().ShouldBe("NOT NULL GENERATED BY DEFAULT AS IDENTITY");
    }

    [Fact]
    public void to_declaration()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.ToDeclaration().ShouldBe("name VARCHAR2(100) NULL");
    }

    [Fact]
    public void equality_based_on_name_and_type()
    {
        var column1 = new TableColumn("name", "VARCHAR2(100)");
        var column2 = new TableColumn("name", "VARCHAR2(100)");
        var column3 = new TableColumn("name", "NUMBER(10)");

        column1.Equals(column2).ShouldBeTrue();
        column1.Equals(column3).ShouldBeFalse();
    }

    [Fact]
    public void raw_type_extracts_type_without_size()
    {
        var column = new TableColumn("name", "VARCHAR2(100)");
        column.RawType().ShouldBe("VARCHAR2");
    }

    [Fact]
    public void add_column_sql()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn("email", "VARCHAR2(200)");

        var column = table.Columns[0];
        column.AddColumnSql(table).ShouldBe("ALTER TABLE WEASEL.PEOPLE ADD email VARCHAR2(200) NULL");
    }

    [Fact]
    public void drop_column_sql()
    {
        var table = new Table("WEASEL.PEOPLE");
        table.AddColumn("email", "VARCHAR2(200)");

        var column = table.Columns[0];
        column.DropColumnSql(table).ShouldBe("ALTER TABLE WEASEL.PEOPLE DROP COLUMN email");
    }
}
