using System.Diagnostics;
using JasperFx.Core;
using JasperFx.Core.Reflection;
using Weasel.Core;

namespace Weasel.Postgresql.Tables;

public class TableColumn: ITableColumn
{
    public TableColumn(string name, string type): this(name, type, false)
    {
    }

    /// <summary>
    ///     PostgreSQL folds unquoted identifiers to lowercase, so by default the
    ///     column name is lowercased to match the historical Weasel/Marten
    ///     convention. Pass <paramref name="preserveCase" /> = true to keep the
    ///     exact name for tables that must reproduce a schema created with
    ///     quoted, case-sensitive identifiers (see <see cref="Core.ITable.PreserveIdentifierCase" />).
    /// </summary>
    public TableColumn(string name, string type, bool preserveCase)
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentOutOfRangeException(nameof(name));
        }

        if (string.IsNullOrEmpty(type))
        {
            throw new ArgumentOutOfRangeException(nameof(type));
        }

        Name = preserveCase
            ? name.Trim()
            : name.ToLowerInvariant().Trim().Replace(' ', '_');
        Type = type.ToLowerInvariant();
    }


    public IList<ColumnCheck> ColumnChecks { get; } = new List<ColumnCheck>();

    public bool AllowNulls { get; set; } = true;

    public string? DefaultExpression { get; set; }

    /// <summary>
    ///     Emits GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+), the modern
    ///     replacement for the serial pseudo-types. BY DEFAULT (rather than
    ///     ALWAYS) so explicit values can still be inserted.
    /// </summary>
    public bool IsAutoNumber { get; set; }

    /// <summary>
    ///     Computed / generated column expression. PostgreSQL only supports
    ///     STORED generated columns, so this always emits
    ///     GENERATED ALWAYS AS (expr) STORED regardless of
    ///     <see cref="ComputedColumnIsStored" />.
    /// </summary>
    public string? ComputedExpression { get; set; }

    public bool ComputedColumnIsStored { get; set; } = true;


    public string Type { get; set; }
    public Table Parent { get; internal set; } = null!;

    public bool IsPrimaryKey { get; internal set; }

    public string Name { get; }

    public string QuotedName => SchemaUtils.QuoteName(Name);

    public string RawType()
    {
        // Remove any parenthesized size/precision segment wherever it appears:
        // "varchar(200)" -> "varchar", but also mid-type forms like
        // "timestamp(3) with time zone" -> "timestamp with time zone"
        var raw = System.Text.RegularExpressions.Regex.Replace(Type, @"\([^)]*\)", "");
        return System.Text.RegularExpressions.Regex.Replace(raw, @"\s+", " ").Trim();
    }

    public string Declaration()
    {
        var declaration = !IsPrimaryKey && AllowNulls ? "NULL" : "NOT NULL";
        if (IsAutoNumber)
        {
            declaration += " GENERATED BY DEFAULT AS IDENTITY";
        }

        if (ComputedExpression.IsNotEmpty())
        {
            declaration += $" GENERATED ALWAYS AS ({ComputedExpression}) STORED";
        }

        if (DefaultExpression.IsNotEmpty())
        {
            declaration += " DEFAULT " + DefaultExpression;
        }

        return $"{declaration} {ColumnChecks.Select(x => x.FullDeclaration()).Join(" ")}".TrimEnd();
    }

    /// <summary>
    ///     Drift comparison for <see cref="Core.ITable.DetectColumnDrift" />:
    ///     nullability (primary key columns excluded — they are implicitly NOT
    ///     NULL) and canonicalized default expressions.
    /// </summary>
    internal bool HasSameDefaultAndNullability(TableColumn actual)
    {
        if (!IsPrimaryKey && !actual.IsPrimaryKey && AllowNulls != actual.AllowNulls)
        {
            return false;
        }

        return canonicalDefault(DefaultExpression) == canonicalDefault(actual.DefaultExpression);
    }

    private static string? canonicalDefault(string? expression)
        => expression == null ? null : TableCheckConstraint.Canonicalize(expression);

    internal void WriteDriftCorrections(Table parent, TableColumn actual, TextWriter writer)
    {
        if (!IsPrimaryKey && !actual.IsPrimaryKey && AllowNulls != actual.AllowNulls)
        {
            writer.WriteLine(
                $"alter table {parent.Identifier} alter column {QuotedName} {(AllowNulls ? "drop not null" : "set not null")};");
        }

        if (canonicalDefault(DefaultExpression) != canonicalDefault(actual.DefaultExpression))
        {
            writer.WriteLine(DefaultExpression.IsNotEmpty()
                ? $"alter table {parent.Identifier} alter column {QuotedName} set default {DefaultExpression};"
                : $"alter table {parent.Identifier} alter column {QuotedName} drop default;");
        }
    }

    protected bool Equals(TableColumn other)
    {
        // Name comparison is case-insensitive: an expected case-preserved column
        // ("Id") must match the same column read back from the catalog regardless
        // of whether it was created quoted ("Id") or folded (id).
        return string.Equals(Name, other.Name, StringComparison.OrdinalIgnoreCase) &&
               string.Equals(PostgresqlProvider.Instance.ConvertSynonyms(RawType()),
                   PostgresqlProvider.Instance.ConvertSynonyms(other.RawType()));
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (!obj.GetType().CanBeCastTo<TableColumn>())
        {
            return false;
        }

        return Equals((TableColumn)obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (StringComparer.OrdinalIgnoreCase.GetHashCode(Name) * 397) ^ Type.GetHashCode();
        }
    }

    public string ToDeclaration()
    {
        var declaration = Declaration();

        return declaration.IsEmpty()
            ? $"{QuotedName} {Type}"
            : $"{QuotedName} {Type} {declaration}";
    }

    public override string ToString()
    {
        return ToDeclaration();
    }


    public virtual string AlterColumnTypeSql(Table table, TableColumn changeActual)
    {
        return $"alter table {table.Identifier} alter column {QuotedName.PadRight(QuotedName.Length)} type {Type};";
    }

    public string DropColumnSql(Table table)
    {
        return $"alter table {table.Identifier} drop column {QuotedName};";
    }


    public virtual bool CanAdd()
    {
        return AllowNulls || DefaultExpression.IsNotEmpty();
    }

    public virtual string AddColumnSql(Table parent)
    {
        return $"alter table {parent.Identifier} add column {ToDeclaration()};";
    }


    public virtual bool CanAlter(TableColumn actual)
    {
        // TODO -- need this to be more systematic
        return true;
    }

    public string ToFunctionArgumentDeclaration()
    {
        if (Type.StartsWith("varchar", StringComparison.OrdinalIgnoreCase))
        {
            return $"{ToArgumentName()} text";
        }

        if (Type.StartsWith("nvarchar", StringComparison.OrdinalIgnoreCase))
        {
            return $"{ToArgumentName()} nvarchar";
        }

        return $"{ToArgumentName()} {Type}";
    }

    public string ToArgumentName()
    {
        return "p_" + Name;
    }

    public string ToFunctionUpdate()
    {
        return $"{QuotedName} = {ToArgumentName()}";
    }
}

public abstract class ColumnCheck
{
    /// <summary>
    ///     The database name for the check. This can be null
    /// </summary>
    public string? Name { get; set; } // TODO -- validate good name

    public abstract string Declaration();

    public string FullDeclaration()
    {
        if (Name.IsEmpty())
        {
            return Declaration();
        }

        return $"CONSTRAINT {Name} {Declaration()}";
    }
}

public class SerialValue : ColumnCheck
{
    public override string Declaration() => "SERIAL";
}

public class BigSerialValue : ColumnCheck
{
    public override string Declaration() => "BIGSERIAL";
}

public class SmallSerialValue: ColumnCheck
{
    public override string Declaration() => "SMALLSERIAL";
}

/*

public class GeneratedAlwaysAsStored : ColumnCheck
{
    // GENERATED ALWAYS AS ( generation_expr ) STORED
}

public class GeneratedAsIdentity : ColumnCheck
{
    // GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ]
}

*/
