namespace Weasel.Core;

public interface INamed
{
    string Name { get; }
}

public interface ITableColumn : INamed
{
    bool AllowNulls { get; set; }
    string? DefaultExpression { get; set; }
    string Type { get; set; }
    bool IsPrimaryKey { get; }

    /// <summary>
    ///     When true, the database generates this column's value on insert:
    ///     IDENTITY on SQL Server, GENERATED BY DEFAULT AS IDENTITY on
    ///     PostgreSQL and Oracle, AUTO_INCREMENT on MySQL, AUTOINCREMENT on
    ///     SQLite.
    /// </summary>
    bool IsAutoNumber { get; set; }
}

public interface ITable : ISchemaObject
{
    IReadOnlyList<string> PrimaryKeyColumns { get; }
    string PrimaryKeyName { get; set; }

    /// <summary>
    ///     When true, column names added to this table keep their exact casing
    ///     instead of being folded to the provider's conventional casing
    ///     (e.g. lowercase on PostgreSQL). Needed when the table definition must
    ///     reproduce a schema created by another tool that quotes identifiers —
    ///     EF Core migrations being the canonical case: EF emits quoted
    ///     PascalCase identifiers, so a case-folded Weasel table would be
    ///     unusable by the EF runtime. Defaults to false.
    /// </summary>
    bool PreserveIdentifierCase { get; set; }
    bool HasColumn(string columnName);
    void RemoveColumn(string columnName);

    ITableColumn AddColumn(string name, string columnType);
    ITableColumn AddColumn(string name, Type dotnetType);

    ITableColumn AddPrimaryKeyColumn(string name, string columnType);
    ITableColumn AddPrimaryKeyColumn(string name, Type dotnetType);

    /// <summary>
    /// The foreign key constraints defined for this table
    /// </summary>
    IReadOnlyList<ForeignKeyBase> ForeignKeys { get; }

    /// <summary>
    /// Add a foreign key constraint to this table
    /// </summary>
    ForeignKeyBase AddForeignKey(string name, DbObjectName linkedTable, string[] columnNames, string[] linkedColumnNames);

    /// <summary>
    /// The indexes defined for this table
    /// </summary>
    IReadOnlyList<ITableIndex> Indexes { get; }

    /// <summary>
    /// Add an index over the given columns to this table
    /// </summary>
    ITableIndex AddIndex(string name, string[] columnNames, bool isUnique = false);
}
