namespace Weasel.Core;

public interface INamed
{
    string Name { get; }
}

public interface ITableColumn : INamed
{
    bool AllowNulls { get; set; }
    string? DefaultExpression { get; set; }
    string Type { get; set; }
    bool IsPrimaryKey { get; }

    /// <summary>
    ///     When true, the database generates this column's value on insert:
    ///     IDENTITY on SQL Server, GENERATED BY DEFAULT AS IDENTITY on
    ///     PostgreSQL and Oracle, AUTO_INCREMENT on MySQL, AUTOINCREMENT on
    ///     SQLite.
    /// </summary>
    bool IsAutoNumber { get; set; }

    /// <summary>
    ///     When set, this is a computed / generated column defined by the given
    ///     SQL expression (without wrapping parentheses). Providers without
    ///     computed-column emission throw when generating DDL for it.
    /// </summary>
    string? ComputedExpression { get; set; }

    /// <summary>
    ///     Whether the computed column is physically stored (PERSISTED /
    ///     STORED) rather than evaluated on read. PostgreSQL only supports
    ///     stored generated columns.
    /// </summary>
    bool ComputedColumnIsStored { get; set; }
}

public interface ITable : ISchemaObject
{
    /// <summary>
    /// The columns defined for this table, in declaration order
    /// </summary>
    IReadOnlyList<ITableColumn> Columns { get; }

    IReadOnlyList<string> PrimaryKeyColumns { get; }
    string PrimaryKeyName { get; set; }

    /// <summary>
    ///     Opt-in detection of column metadata drift: when true, delta detection
    ///     also compares column default expressions and nullability for columns
    ///     that otherwise match, emitting ALTER statements to correct drift.
    ///     Off by default because default expressions are compared textually
    ///     after canonicalization — literal formats that the database rewrites
    ///     non-trivially (notably datetime literals) can produce perpetual
    ///     false-positive migrations. Enable it for tables whose defaults are
    ///     simple numeric / string / boolean literals or stable function calls.
    /// </summary>
    bool DetectColumnDrift { get; set; }

    /// <summary>
    ///     When true, column names added to this table keep their exact casing
    ///     instead of being folded to the provider's conventional casing
    ///     (e.g. lowercase on PostgreSQL). Needed when the table definition must
    ///     reproduce a schema created by another tool that quotes identifiers —
    ///     EF Core migrations being the canonical case: EF emits quoted
    ///     PascalCase identifiers, so a case-folded Weasel table would be
    ///     unusable by the EF runtime. Defaults to false.
    /// </summary>
    bool PreserveIdentifierCase { get; set; }

    /// <summary>
    ///     When true, a migration for this table never drops a column, index or foreign key that
    ///     the model does not declare. Additive and in-place changes still apply: a new column is
    ///     added, a changed index is recreated, a widened type is altered -- only the removal of
    ///     something undeclared is withheld. Defaults to false.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///     For a table defined directly in code, the model is the whole truth about the schema and
    ///     dropping what it no longer declares is the point. For a table <em>translated</em> from
    ///     another model it is not: a column the source model knows about and the translator could
    ///     not express is not "removed", it is "not understood", and the right answer is to leave it
    ///     alone. That turns every gap in a translation layer into a data-loss branch, which is why
    ///     tables mapped from an EF Core model set this by default (weasel#629).
    ///     </para>
    ///     <para>
    ///     Withheld drops are reported through
    ///     <see cref="ISchemaObjectDeltaWithWithheldDrops" />, and logged once per table before a
    ///     migration runs, so the omission is visible rather than silent. A schema whose ONLY
    ///     difference is a withheld drop has nothing to migrate and is not warned about -- that
    ///     line would otherwise appear on every application start for as long as the column
    ///     exists; read the delta, or use the reporting commands, for the quiet case.
    ///     </para>
    /// </remarks>
    bool AddOnlyMigrations { get; set; }
    bool HasColumn(string columnName);
    void RemoveColumn(string columnName);

    ITableColumn AddColumn(string name, string columnType);
    ITableColumn AddColumn(string name, Type dotnetType);

    ITableColumn AddPrimaryKeyColumn(string name, string columnType);
    ITableColumn AddPrimaryKeyColumn(string name, Type dotnetType);

    /// <summary>
    /// The foreign key constraints defined for this table
    /// </summary>
    IReadOnlyList<ForeignKeyBase> ForeignKeys { get; }

    /// <summary>
    /// Add a foreign key constraint to this table
    /// </summary>
    ForeignKeyBase AddForeignKey(string name, DbObjectName linkedTable, string[] columnNames, string[] linkedColumnNames);

    /// <summary>
    /// The indexes defined for this table
    /// </summary>
    IReadOnlyList<ITableIndex> Indexes { get; }

    /// <summary>
    /// Add an index over the given columns to this table
    /// </summary>
    ITableIndex AddIndex(string name, string[] columnNames, bool isUnique = false);

    /// <summary>
    /// The named table-level CHECK constraints declared for this table
    /// </summary>
    IReadOnlyList<TableCheckConstraint> CheckConstraints { get; }

    /// <summary>
    /// Declare a named table-level CHECK constraint on this table
    /// </summary>
    TableCheckConstraint AddCheckConstraint(string name, string expression);
}
