<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Weasel.SqlServer\Weasel.SqlServer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <Import Project="../../Tests.Build.props" />
</Project>
