using System.Text;
using System.Text.RegularExpressions;
using JasperFx.Core;
using Weasel.Core;

namespace Weasel.Firebird.Tables;

public class TableColumn: ITableColumn
{
    private static readonly Regex CollateClause =
        new(@"\s+COLLATE\s+(\S+)\s*$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    private static readonly Regex DefaultKeyword =
        new(@"^\s*DEFAULT\b", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public TableColumn(string name, string type)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentOutOfRangeException(nameof(name));
        }

        if (string.IsNullOrWhiteSpace(type))
        {
            throw new ArgumentOutOfRangeException(nameof(type));
        }

        // Undelimited on the way in: a caller who wrote "Order Date" means the column Order Date,
        // and the model has to hold the name the catalog will report back (weasel#458, weasel#499).
        Name = SchemaUtils.Unquote(name.Trim());
        Type = type.Trim();
    }

    public string Name { get; }

    /// <summary>
    ///     The column's type as the model writes it, synonyms and all -- <c>INT</c>,
    ///     <c>VARCHAR(100) CHARACTER SET UTF8 COLLATE UNICODE_CI</c>. It is compared through
    ///     <see cref="FirebirdColumnType" />, so any spelling of the same type matches.
    /// </summary>
    public string Type { get; set; }

    public bool AllowNulls { get; set; } = true;

    /// <summary>
    ///     The default, as the expression after <c>DEFAULT</c>. <c>NULL</c> is the same as no default,
    ///     on both sides of a comparison.
    /// </summary>
    public string? DefaultExpression { get; set; }

    public bool IsPrimaryKey { get; internal set; }

    /// <summary>
    ///     An identity column, written <c>GENERATED BY DEFAULT AS IDENTITY NOT NULL</c> -- in that order,
    ///     because Firebird refuses <c>NOT NULL</c> before it. Whether a column is an identity is not
    ///     compared, as on Oracle: Firebird 3 does not record which kind of identity a column is.
    /// </summary>
    public bool IsAutoNumber { get; set; }

    /// <summary>
    ///     Not supported: Firebird has only virtual computed columns (<c>COMPUTED BY</c>), and Weasel
    ///     does not write or compare them yet. Rendering a column with this set throws rather than
    ///     silently creating a plain column.
    /// </summary>
    public string? ComputedExpression { get; set; }

    public bool ComputedColumnIsStored { get; set; }

    public Table? Parent { get; internal set; }

    private bool preserveCase => Parent?.PreserveIdentifierCase ?? false;

    public string QuotedName => SchemaUtils.QuoteName(Name, preserveCase);

    /// <summary>
    ///     The name as Firebird's catalog stores it.
    /// </summary>
    internal string CatalogName => SchemaUtils.CatalogName(Name, preserveCase);

    /// <summary>
    ///     Whether the column takes NULL: not part of the primary key, not an identity, and not declared
    ///     <c>NOT NULL</c>.
    /// </summary>
    internal bool AcceptsNulls => !IsPrimaryKey && !IsAutoNumber && AllowNulls;

    /// <summary>
    ///     The type without a trailing <c>COLLATE</c>, which Firebird wants last in a column definition,
    ///     after the default and <c>NOT NULL</c>.
    /// </summary>
    public string DeclaredType => splitCollation().Type;

    /// <summary>
    ///     The collation the type names, if it names one.
    /// </summary>
    public string? Collation => splitCollation().Collation;

    public string RawType() => Type.Split('(')[0].Trim().ToUpperInvariant();

    /// <summary>
    ///     This column's type folded onto the catalog spelling, for a comparison with a server of
    ///     <paramref name="version" />.
    /// </summary>
    internal FirebirdColumnType ColumnType(FirebirdServerVersion? version = null)
        => FirebirdColumnType.Parse(Type, version);

    /// <summary>
    ///     Everything after the type in a column definition: the default or the identity clause,
    ///     <c>NOT NULL</c>, and the collation.
    /// </summary>
    public string Declaration()
    {
        if (ComputedExpression != null)
        {
            throw new NotSupportedException(
                $"Column '{Name}' is computed. Weasel.Firebird does not write or compare computed (COMPUTED BY) columns yet.");
        }

        var parts = new List<string>();

        if (IsAutoNumber)
        {
            if (hasDefault(DefaultExpression))
            {
                throw new InvalidOperationException(
                    $"Column '{Name}' is an identity column and cannot also have a default. Firebird generates its value.");
            }

            parts.Add("GENERATED BY DEFAULT AS IDENTITY");
            parts.Add("NOT NULL");
        }
        else
        {
            if (DefaultExpression.IsNotEmpty())
            {
                parts.Add("DEFAULT " + DefaultExpression);
            }

            if (!AllowNulls || IsPrimaryKey)
            {
                parts.Add("NOT NULL");
            }
        }

        var collation = Collation;
        if (collation != null)
        {
            parts.Add("COLLATE " + collation);
        }

        return parts.Join(" ");
    }

    public string ToDeclaration()
    {
        return $"{QuotedName} {DeclaredType} {Declaration()}".TrimEnd();
    }

    public override string ToString()
    {
        return ToDeclaration();
    }

    /// <summary>
    ///     Does <paramref name="actual" /> -- read from the catalog -- have this column's type?
    ///     Arguments the model leaves out, a character set or a collation say, are not compared.
    /// </summary>
    internal bool TypeMatches(TableColumn actual, FirebirdServerVersion? version)
        => ColumnType(version).IsSatisfiedBy(actual.ColumnType(version));

    /// <summary>
    ///     Does <paramref name="actual" /> have this column's default? <c>DEFAULT NULL</c> in any spelling
    ///     is no default, and keyword case and whitespace outside a literal do not count.
    /// </summary>
    internal bool DefaultMatches(TableColumn actual)
        => NormalizeDefault(DefaultExpression) == NormalizeDefault(actual.DefaultExpression);

    internal bool NullabilityMatches(TableColumn actual) => AcceptsNulls == actual.AcceptsNulls;

    public bool IsEquivalentTo(TableColumn other)
    {
        return Name.Equals(other.Name, StringComparison.OrdinalIgnoreCase) && TypeMatches(other, null);
    }

    public override bool Equals(object? obj) => obj is TableColumn other && IsEquivalentTo(other);

    public override int GetHashCode()
        => HashCode.Combine(Name.ToUpperInvariant(), FirebirdColumnType.Parse(Type).Name);

    /// <summary>
    ///     A default in the form it is compared in: without a leading <c>DEFAULT</c> keyword -- the
    ///     catalog stores the whole clause, as written -- with whitespace collapsed and letters folded
    ///     outside string literals, and <c>NULL</c> as no default at all.
    /// </summary>
    internal static string? NormalizeDefault(string? expression)
    {
        if (expression.IsEmpty())
        {
            return null;
        }

        var text = DefaultKeyword.Replace(expression!, "").Trim();

        var builder = new StringBuilder(text.Length);
        var inLiteral = false;
        var pendingSpace = false;

        foreach (var c in text)
        {
            if (c == '\'')
            {
                inLiteral = !inLiteral;
            }

            if (!inLiteral && char.IsWhiteSpace(c))
            {
                pendingSpace = builder.Length > 0;
                continue;
            }

            if (pendingSpace)
            {
                builder.Append(' ');
                pendingSpace = false;
            }

            builder.Append(inLiteral ? c : char.ToUpperInvariant(c));
        }

        var normalized = builder.ToString();
        return normalized.Length == 0 || normalized == "NULL" ? null : normalized;
    }

    /// <summary>
    ///     The default text as the catalog stores it, <c>DEFAULT 'x'</c>, reduced to the expression, or
    ///     null when there is none -- including <c>DEFAULT NULL</c>, which is how Quartz spells "none".
    /// </summary>
    internal static string? ReadDefault(string? source)
    {
        if (source.IsEmpty())
        {
            return null;
        }

        var expression = DefaultKeyword.Replace(source!, "").Trim();
        return NormalizeDefault(expression) == null ? null : expression;
    }

    private static bool hasDefault(string? expression) => NormalizeDefault(expression) != null;

    private (string Type, string? Collation) splitCollation()
    {
        var match = CollateClause.Match(Type);
        return match.Success ? (Type[..match.Index].TrimEnd(), match.Groups[1].Value) : (Type, null);
    }

    /// <summary>
    ///     <c>ALTER TABLE … ADD</c> for this column, guarded so it runs once however often, and however
    ///     many appliers race it. Firebird's syntax is <c>ADD c</c>; <c>ADD COLUMN</c> is a syntax error.
    /// </summary>
    internal string AddColumnSql(Table parent)
        => FirebirdScript.Guarded(CatalogProbes.Column(parent.CatalogName, CatalogName),
            $"ALTER TABLE {parent.QuotedName} ADD {ToDeclaration()}");

    /// <summary>
    ///     <c>ALTER TABLE … DROP</c> for this column, run only while it exists. <c>DROP COLUMN</c> is a
    ///     syntax error.
    /// </summary>
    internal string DropColumnSql(Table parent)
        => FirebirdScript.Guarded(CatalogProbes.Column(parent.CatalogName, CatalogName),
            $"ALTER TABLE {parent.QuotedName} DROP {QuotedName}", whenExists: true);

    internal string AlterTypeSql(Table parent)
        => $"ALTER TABLE {parent.QuotedName} ALTER {QuotedName} TYPE {DeclaredType}";

    internal string AlterNullabilitySql(Table parent)
        => $"ALTER TABLE {parent.QuotedName} ALTER {QuotedName} {(AcceptsNulls ? "DROP" : "SET")} NOT NULL";

    internal string AlterDefaultSql(Table parent)
        => hasDefault(DefaultExpression)
            ? $"ALTER TABLE {parent.QuotedName} ALTER {QuotedName} SET DEFAULT {DefaultExpression}"
            : $"ALTER TABLE {parent.QuotedName} ALTER {QuotedName} DROP DEFAULT";

    /// <summary>
    ///     Can this column be added to a table that already exists? Firebird refuses a <c>NOT NULL</c>
    ///     column without a default on a table with rows, and an identity column on a table with rows
    ///     (335544989); whether the table has rows cannot be known when the change is planned, so both
    ///     are refused up front, as Oracle refuses the first.
    /// </summary>
    public virtual bool CanAdd()
    {
        if (IsAutoNumber)
        {
            return false;
        }

        return AcceptsNulls || hasDefault(DefaultExpression);
    }
}
