using FirebirdSql.Data.FirebirdClient;
using Shouldly;
using Xunit;

namespace Weasel.Firebird.Tests;

/// <summary>
///     Firebird has no server-side cascade, so <c>DropSchemaAsync</c> enumerates -- and an enumerating
///     teardown silently leaves behind whatever kind of object it does not know about (weasel#464,
///     weasel#465). Every kind of object a user can create is created here with raw SQL, the typed
///     objects notwithstanding, and the database has to come out empty.
/// </summary>
public class dropping_schemas_with_every_object_type: IntegrationContext
{
    private const string UserObjectCountSql = """
        SELECT
            (SELECT COUNT(*) FROM RDB$RELATIONS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$TRIGGERS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$PROCEDURES WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$FUNCTIONS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$PACKAGES WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$GENERATORS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$EXCEPTIONS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0)
          + (SELECT COUNT(*) FROM RDB$FIELDS WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0 AND RDB$FIELD_NAME NOT STARTING WITH 'RDB$')
          + (SELECT COUNT(*) FROM RDB$RELATION_CONSTRAINTS rc JOIN RDB$RELATIONS r ON r.RDB$RELATION_NAME = rc.RDB$RELATION_NAME WHERE COALESCE(r.RDB$SYSTEM_FLAG, 0) = 0)
        FROM RDB$DATABASE
        """;

    private async Task createEveryKindOfObjectAsync()
    {
        await ExecuteAsync("""
            CREATE DOMAIN d_positive AS INTEGER CHECK (VALUE > 0);
            CREATE EXCEPTION e_nope 'nope';
            CREATE SEQUENCE s_orders;

            CREATE TABLE customers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(50),
                CONSTRAINT pk_customers PRIMARY KEY (id)
            );

            CREATE TABLE orders (
                id INTEGER NOT NULL,
                customer_id INTEGER,
                quantity d_positive,
                CONSTRAINT pk_orders PRIMARY KEY (id),
                CONSTRAINT ck_orders_id CHECK (id > 0)
            );

            ALTER TABLE orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id);

            CREATE GLOBAL TEMPORARY TABLE scratch (id INTEGER) ON COMMIT DELETE ROWS;

            CREATE VIEW v_orders AS SELECT id, customer_id FROM orders;
            CREATE VIEW v_orders_again AS SELECT id FROM v_orders;

            SET TERM ^ ;
            CREATE PROCEDURE p_inner RETURNS (x INTEGER) AS
            BEGIN
              x = 1;
              SUSPEND;
            END
            ^
            CREATE PROCEDURE p_outer RETURNS (x INTEGER) AS
            BEGIN
              FOR SELECT x FROM p_inner INTO :x DO SUSPEND;
            END
            ^
            CREATE FUNCTION f_double (x INTEGER) RETURNS INTEGER AS
            BEGIN
              RETURN x * 2;
            END
            ^
            CREATE PACKAGE pkg_things AS
            BEGIN
              FUNCTION one RETURNS INTEGER;
            END
            ^
            CREATE PACKAGE BODY pkg_things AS
            BEGIN
              FUNCTION one RETURNS INTEGER AS
              BEGIN
                RETURN 1;
              END
            END
            ^
            CREATE TRIGGER trg_orders FOR orders BEFORE INSERT AS
            BEGIN
              NEW.quantity = COALESCE(NEW.quantity, 1);
            END
            ^
            SET TERM ; ^
            """);
    }

    [Fact]
    public async Task every_kind_of_object_is_dropped()
    {
        await createEveryKindOfObjectAsync();

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBeGreaterThan(10);

        await theConnection.DropSchemaAsync();

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBe(0,
            "every user object has to go, or the next thing that needs an empty database breaks instead");
    }

    [Fact]
    public async Task an_empty_database_stays_empty()
    {
        await theConnection.DropSchemaAsync();

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBe(0);
    }

    /// <summary>
    ///     An idle pooled attachment still holds the tables it touched, and <c>DROP TABLE</c> refuses a
    ///     table in use.
    /// </summary>
    [Fact]
    public async Task an_idle_pooled_connection_does_not_block_the_teardown()
    {
        await ExecuteAsync("CREATE TABLE held (id INTEGER)");

        var pooled = new FbConnectionStringBuilder(ConnectionString) { Pooling = true }.ConnectionString;
        await using (var idle = new FbConnection(pooled))
        {
            await idle.OpenAsync();
            await using var cmd = idle.CreateCommand("SELECT COUNT(*) FROM held");
            await cmd.ExecuteScalarAsync();
        }

        await using var conn = new FbConnection(pooled);
        await conn.DropSchemaAsync();

        (await ScalarAsync<int>("SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'HELD'")).ShouldBe(0);
    }

    [Fact]
    public async Task the_default_schema_by_name_is_the_database()
    {
        await ExecuteAsync("CREATE TABLE t (id INTEGER)");

        await theConnection.DropSchemaAsync("PUBLIC");

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBe(0);
    }

    [Fact]
    public async Task reset_schema_empties_the_database()
    {
        await ExecuteAsync("CREATE TABLE t (id INTEGER)");

        await theConnection.ResetSchemaAsync("public");

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBe(0);
    }

    [Fact]
    public async Task another_schema_is_refused()
    {
        await Should.ThrowAsync<NotSupportedException>(() => theConnection.DropSchemaAsync("sales"));
    }

    [Fact]
    public async Task a_closed_connection_is_opened()
    {
        await ExecuteAsync("CREATE TABLE t (id INTEGER)");

        await using var closed = new FbConnection(ConnectionString);
        await closed.DropSchemaAsync();

        (await ScalarAsync<int>(UserObjectCountSql)).ShouldBe(0);
    }
}
