<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" VersionOverride="10.0.0" />
        <PackageReference Include="Npgsql.NetTopologySuite" VersionOverride="10.0.0" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Weasel.Postgresql\Weasel.Postgresql.csproj" />
    </ItemGroup>

    <Import Project="../../Tests.Build.props" />
</Project>
