using Shouldly;
using Weasel.Firebird.Tables;
using Xunit;

namespace Weasel.Firebird.Tests.Tables;

public class TableColumnTests
{
    private static Table parent(bool preserveCase = false) => new("orders") { PreserveIdentifierCase = preserveCase };

    private static TableColumn column(string name, string type, Action<TableColumn>? configure = null)
    {
        var table = parent();
        var column = new TableColumn(name, type);
        table.AddColumn(column);
        configure?.Invoke(column);
        return column;
    }

    [Fact]
    public void a_nullable_column_says_nothing_about_nulls()
    {
        column("name", "VARCHAR(100)").ToDeclaration().ShouldBe("name VARCHAR(100)");
    }

    [Fact]
    public void the_default_comes_before_not_null()
    {
        column("state", "INTEGER", x =>
        {
            x.AllowNulls = false;
            x.DefaultExpression = "0";
        }).ToDeclaration().ShouldBe("state INTEGER DEFAULT 0 NOT NULL");
    }

    [Fact]
    public void a_primary_key_column_is_not_null()
    {
        var table = parent();
        table.AddColumn<int>("id").AsPrimaryKey();

        table.Columns.Single().ToDeclaration().ShouldBe("id INTEGER NOT NULL");
    }

    /// <summary>
    ///     Firebird wants the collation last, after the default and NOT NULL; a model writes it as part
    ///     of the type.
    /// </summary>
    [Fact]
    public void the_collation_is_written_last()
    {
        var declaration = column("name", "VARCHAR(100) CHARACTER SET UTF8 COLLATE UNICODE_CI", x =>
        {
            x.AllowNulls = false;
            x.DefaultExpression = "'x'";
        }).ToDeclaration();

        declaration.ShouldBe("name VARCHAR(100) CHARACTER SET UTF8 DEFAULT 'x' NOT NULL COLLATE UNICODE_CI");
    }

    [Fact]
    public void the_declared_type_and_the_collation_are_split()
    {
        var subject = column("name", "varchar(10) collate unicode_ci");

        subject.DeclaredType.ShouldBe("varchar(10)");
        subject.Collation.ShouldBe("unicode_ci");
    }

    /// <summary>
    ///     A4: Firebird refuses <c>NOT NULL GENERATED …</c>; identity comes first.
    /// </summary>
    [Fact]
    public void an_identity_is_written_before_not_null()
    {
        var table = parent();
        table.AddColumn<long>("id").AsPrimaryKey().AutoIncrement();

        table.Columns.Single().ToDeclaration().ShouldBe("id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL");
    }

    [Fact]
    public void an_identity_with_a_default_is_refused()
    {
        var subject = column("id", "INTEGER", x =>
        {
            x.IsAutoNumber = true;
            x.DefaultExpression = "1";
        });

        Should.Throw<InvalidOperationException>(() => subject.Declaration()).Message.ShouldContain("identity");
    }

    [Fact]
    public void an_identity_with_a_null_default_is_fine()
    {
        column("id", "INTEGER", x =>
        {
            x.IsAutoNumber = true;
            x.DefaultExpression = "NULL";
        }).Declaration().ShouldBe("GENERATED BY DEFAULT AS IDENTITY NOT NULL");
    }

    [Fact]
    public void a_computed_column_is_refused_rather_than_written_as_a_plain_one()
    {
        var subject = column("total", "INTEGER", x => x.ComputedExpression = "a + b");

        Should.Throw<NotSupportedException>(() => subject.ToDeclaration()).Message.ShouldContain("COMPUTED BY");
    }

    [Theory]
    [InlineData("\"order date\"", "order date")]
    [InlineData("  name  ", "name")]
    [InlineData("\"A\"\"B\"", "A\"B")]
    public void the_name_is_held_undelimited(string written, string held)
    {
        new TableColumn(written, "INTEGER").Name.ShouldBe(held);
    }

    [Theory]
    [InlineData("name", "name")]
    [InlineData("value", "\"VALUE\"")]
    [InlineData("order date", "\"ORDER DATE\"")]
    public void the_name_is_quoted_where_firebird_needs_it(string name, string quoted)
    {
        column(name, "INTEGER").QuotedName.ShouldBe(quoted);
    }

    [Fact]
    public void a_case_preserving_table_delimits_the_name_exactly()
    {
        var table = parent(preserveCase: true);
        var subject = new TableColumn("BlogId", "INTEGER");
        table.AddColumn(subject);

        subject.QuotedName.ShouldBe("\"BlogId\"");
        subject.CatalogName.ShouldBe("BlogId");
    }

    [Theory]
    [InlineData("", null)]
    [InlineData("NULL", null)]
    [InlineData("null", null)]
    [InlineData("DEFAULT NULL", null)]
    [InlineData("default   null", null)]
    [InlineData("DEFAULT 'x'", "'x'")]
    [InlineData("DEFAULT    'x'", "'x'")]
    [InlineData("'it''s'", "'it''s'")]
    [InlineData("current_timestamp", "CURRENT_TIMESTAMP")]
    [InlineData("'Mixed  Case'", "'Mixed  Case'")]
    [InlineData("DEFAULT 0", "0")]
    public void a_default_is_compared_without_its_keyword_whitespace_or_case(string written, string? normalized)
    {
        TableColumn.NormalizeDefault(written).ShouldBe(normalized);
    }

    [Theory]
    [InlineData(null, null)]
    [InlineData("DEFAULT NULL", null)]
    [InlineData("default null", null)]
    [InlineData("DEFAULT  NULL", null)]
    [InlineData("DEFAULT 'it''s'", "'it''s'")]
    [InlineData("DEFAULT 0", "0")]
    public void a_default_read_from_the_catalog_loses_its_keyword_and_null_means_none(string? source, string? read)
    {
        TableColumn.ReadDefault(source).ShouldBe(read);
    }

    [Fact]
    public void a_default_matches_however_it_was_spelled()
    {
        var model = column("state", "INTEGER", x => x.DefaultExpression = "CURRENT_TIMESTAMP");
        var catalog = column("STATE", "INTEGER", x => x.DefaultExpression = "current_timestamp");

        model.DefaultMatches(catalog).ShouldBeTrue();
    }

    [Fact]
    public void a_null_default_matches_no_default()
    {
        var model = column("description", "VARCHAR(250)", x => x.DefaultExpression = "NULL");
        var catalog = column("DESCRIPTION", "VARCHAR(250)");

        model.DefaultMatches(catalog).ShouldBeTrue();
    }

    [Fact]
    public void a_type_matches_through_its_synonyms()
    {
        column("id", "INT").TypeMatches(column("ID", "INTEGER"), null).ShouldBeTrue();
        column("id", "INT").TypeMatches(column("ID", "BIGINT"), null).ShouldBeFalse();
    }

    [Fact]
    public void nullability_counts_a_key_or_an_identity_as_not_null()
    {
        var table = parent();
        table.AddColumn<int>("id").AsPrimaryKey();
        var key = table.Columns.Single();

        var notNull = column("ID", "INTEGER", x => x.AllowNulls = false);

        key.NullabilityMatches(notNull).ShouldBeTrue();
        column("id", "INTEGER").NullabilityMatches(notNull).ShouldBeFalse();
    }

    [Fact]
    public void a_nullable_column_or_one_with_a_default_can_be_added()
    {
        column("a", "INTEGER").CanAdd().ShouldBeTrue();
        column("a", "INTEGER", x =>
        {
            x.AllowNulls = false;
            x.DefaultExpression = "0";
        }).CanAdd().ShouldBeTrue();
    }

    /// <summary>
    ///     Firebird refuses both on a table with rows (335544989 for the identity), and whether the
    ///     table has rows cannot be known when the migration is planned.
    /// </summary>
    [Fact]
    public void a_not_null_column_without_a_default_or_an_identity_cannot_be_added()
    {
        column("a", "INTEGER", x => x.AllowNulls = false).CanAdd().ShouldBeFalse();
        column("a", "INTEGER", x => x.DefaultExpression = "NULL").CanAdd().ShouldBeTrue();
        column("a", "INTEGER", x =>
        {
            x.AllowNulls = false;
            x.DefaultExpression = "NULL";
        }).CanAdd().ShouldBeFalse();
        column("a", "INTEGER", x => x.IsAutoNumber = true).CanAdd().ShouldBeFalse();
    }

    /// <summary>
    ///     A4: Firebird's syntax is <c>ADD c</c>; <c>ADD COLUMN</c> is a syntax error.
    /// </summary>
    [Fact]
    public void adding_a_column_is_guarded_and_never_says_column()
    {
        var table = parent();
        table.AddColumn("note", "VARCHAR(20)").DefaultValueByString("it's");

        var sql = table.Columns.Single().AddColumnSql(table);

        sql.ShouldContain("RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'ORDERS' AND RDB$FIELD_NAME = 'NOTE'");
        sql.ShouldContain("EXECUTE STATEMENT 'ALTER TABLE orders ADD note VARCHAR(20) DEFAULT ''it''''s''';");
        sql.ShouldNotContain("ADD COLUMN");
    }

    [Fact]
    public void dropping_a_column_is_guarded_and_never_says_column()
    {
        var table = parent();
        table.AddColumn("note", "VARCHAR(20)");

        var sql = table.Columns.Single().DropColumnSql(table);

        sql.ShouldContain("IF (EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS");
        sql.ShouldContain("'ALTER TABLE orders DROP note'");
    }

    [Fact]
    public void altering_a_type_leaves_the_collation_out()
    {
        var table = parent();
        table.AddColumn("note", "VARCHAR(40) COLLATE UNICODE_CI");

        table.Columns.Single().AlterTypeSql(table).ShouldBe("ALTER TABLE orders ALTER note TYPE VARCHAR(40)");
    }

    [Fact]
    public void altering_nullability_sets_or_drops_not_null()
    {
        var table = parent();
        table.AddColumn("a", "INTEGER").NotNull();
        table.AddColumn("b", "INTEGER");

        table.Columns[0].AlterNullabilitySql(table).ShouldBe("ALTER TABLE orders ALTER a SET NOT NULL");
        table.Columns[1].AlterNullabilitySql(table).ShouldBe("ALTER TABLE orders ALTER b DROP NOT NULL");
    }

    [Fact]
    public void altering_a_default_sets_or_drops_it()
    {
        var table = parent();
        table.AddColumn("a", "INTEGER").DefaultValue(5);
        table.AddColumn("b", "INTEGER").DefaultValueByExpression("NULL");

        table.Columns[0].AlterDefaultSql(table).ShouldBe("ALTER TABLE orders ALTER a SET DEFAULT 5");
        table.Columns[1].AlterDefaultSql(table).ShouldBe("ALTER TABLE orders ALTER b DROP DEFAULT");
    }

    [Fact]
    public void equality_is_by_name_and_type()
    {
        column("id", "INT").ShouldBe(column("ID", "INTEGER"));
        column("id", "INT").GetHashCode().ShouldBe(column("ID", "INTEGER").GetHashCode());
        column("id", "INT").ShouldNotBe(column("id", "BIGINT"));
    }

    [Fact]
    public void raw_type_is_the_type_name()
    {
        column("a", "varchar(10)").RawType().ShouldBe("VARCHAR");
    }

    [Fact]
    public void a_blank_name_or_type_is_refused()
    {
        Should.Throw<ArgumentOutOfRangeException>(() => new TableColumn(" ", "INTEGER"));
        Should.Throw<ArgumentOutOfRangeException>(() => new TableColumn("a", " "));
    }
}
