using JasperFx.Core;
using JasperFx.Core.Reflection;
using Weasel.Core;

namespace Weasel.Oracle.Tables;

public class TableColumn: ITableColumn
{
    private readonly bool _preserveCase;

    public TableColumn(string name, string type): this(name, type, false)
    {
    }

    /// <summary>
    ///     Oracle folds unquoted identifiers to UPPERCASE; by default the column
    ///     name is lowercased and written unquoted (the historical Weasel
    ///     convention, stored by Oracle as uppercase). Pass
    ///     <paramref name="preserveCase" /> = true to keep the exact name and
    ///     emit it quoted, for tables that must reproduce a schema created with
    ///     quoted, case-sensitive identifiers (see <see cref="Core.ITable.PreserveIdentifierCase" />).
    /// </summary>
    public TableColumn(string name, string type, bool preserveCase)
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentOutOfRangeException(nameof(name));
        }

        if (string.IsNullOrEmpty(type))
        {
            throw new ArgumentOutOfRangeException(nameof(type));
        }

        _preserveCase = preserveCase;
        Name = preserveCase
            ? name.Trim()
            : name.ToLowerInvariant().Trim().Replace(' ', '_');
        Type = type.ToUpperInvariant();
    }

    public IList<ColumnCheck> ColumnChecks { get; } = new List<ColumnCheck>();

    public bool AllowNulls { get; set; } = true;

    public string? DefaultExpression { get; set; }

    public string Type { get; set; }
    public Table Parent { get; internal set; } = null!;

    public bool IsPrimaryKey { get; internal set; }
    public bool IsAutoNumber { get; set; }

    /// <summary>
    ///     Computed (virtual) column expression. DDL emission for Oracle virtual
    ///     columns is not implemented yet — generating DDL for a column with
    ///     this set throws rather than silently creating a plain column.
    /// </summary>
    public string? ComputedExpression { get; set; }

    public bool ComputedColumnIsStored { get; set; }

    public string Name { get; }

    public string QuotedName => _preserveCase ? $"\"{Name}\"" : SchemaUtils.QuoteName(Name);

    public string RawType()
    {
        return Type.Split('(')[0].Trim();
    }

    public string Declaration()
    {
        if (ComputedExpression != null)
        {
            throw new NotSupportedException(
                "Computed (virtual) column DDL emission is not implemented for Oracle yet");
        }

        var parts = new List<string>();

        // In Oracle, the order is: DEFAULT, NULL/NOT NULL, IDENTITY, CHECK constraints
        if (DefaultExpression.IsNotEmpty())
        {
            parts.Add("DEFAULT " + DefaultExpression);
        }

        parts.Add(!IsPrimaryKey && AllowNulls ? "NULL" : "NOT NULL");

        if (IsAutoNumber)
        {
            parts.Add("GENERATED BY DEFAULT AS IDENTITY");
        }

        foreach (var check in ColumnChecks)
        {
            parts.Add(check.FullDeclaration());
        }

        return parts.Join(" ");
    }

    protected bool Equals(TableColumn other)
    {
        return string.Equals(QuotedName, other.QuotedName, StringComparison.OrdinalIgnoreCase) &&
               string.Equals(OracleProvider.Instance.ConvertSynonyms(RawType()),
                   OracleProvider.Instance.ConvertSynonyms(other.RawType()), StringComparison.OrdinalIgnoreCase);
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (!obj.GetType().CanBeCastTo<TableColumn>())
        {
            return false;
        }

        return Equals((TableColumn)obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (Name.ToUpperInvariant().GetHashCode() * 397) ^ Type.ToUpperInvariant().GetHashCode();
        }
    }

    public string ToDeclaration()
    {
        var declaration = Declaration();

        return declaration.IsEmpty()
            ? $"{QuotedName} {Type}"
            : $"{QuotedName} {Type} {declaration}";
    }

    public override string ToString()
    {
        return ToDeclaration();
    }

    public virtual string AlterColumnTypeSql(Table table, TableColumn changeActual)
    {
        return $"ALTER TABLE {table.Identifier} MODIFY {changeActual.ToDeclaration()}";
    }

    public string DropColumnSql(Table table)
    {
        return $"ALTER TABLE {table.Identifier} DROP COLUMN {QuotedName}";
    }

    public virtual bool CanAdd()
    {
        return AllowNulls || DefaultExpression.IsNotEmpty();
    }

    public virtual string AddColumnSql(Table parent)
    {
        return $"ALTER TABLE {parent.Identifier} ADD {ToDeclaration()}";
    }

    public virtual bool CanAlter(TableColumn actual)
    {
        return true;
    }
}

public abstract class ColumnCheck
{
    /// <summary>
    ///     The database name for the check. This can be null
    /// </summary>
    public string? Name { get; set; }

    public abstract string Declaration();

    public string FullDeclaration()
    {
        if (Name.IsEmpty())
        {
            return Declaration();
        }

        return $"CONSTRAINT {Name} {Declaration()}";
    }
}

public class SerialValue: ColumnCheck
{
    public override string Declaration()
    {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }
}
