using System.Text.RegularExpressions;
using JasperFx.Core;
using JasperFx.Core.Reflection;
using Weasel.Core;

namespace Weasel.Oracle.Tables;

public class TableColumn: ITableColumn
{
    private readonly bool _preserveCase;

    public TableColumn(string name, string type): this(name, type, false)
    {
    }

    /// <summary>
    ///     Oracle folds unquoted identifiers to UPPERCASE; by default the column
    ///     name is lowercased and written unquoted (the historical Weasel
    ///     convention, stored by Oracle as uppercase). Pass
    ///     <paramref name="preserveCase" /> = true to keep the exact name and
    ///     emit it quoted, for tables that must reproduce a schema created with
    ///     quoted, case-sensitive identifiers (see <see cref="Core.ITable.PreserveIdentifierCase" />).
    /// </summary>
    public TableColumn(string name, string type, bool preserveCase)
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentOutOfRangeException(nameof(name));
        }

        if (string.IsNullOrEmpty(type))
        {
            throw new ArgumentOutOfRangeException(nameof(type));
        }

        _preserveCase = preserveCase;
        // Undelimited first: a caller who wrote "ORDER DATE" means that column, and Oracle
        // reports it back bare. Case folding is what preserveCase turns off, and nothing else --
        // it used to silently turn off a space-to-underscore rewrite as well (weasel#458).
        var unquoted = SchemaUtils.Unquote(name.Trim());

        Name = preserveCase ? unquoted : unquoted.ToLowerInvariant();
        Type = type.ToUpperInvariant();
    }

    public IList<ColumnCheck> ColumnChecks { get; } = new List<ColumnCheck>();

    public bool AllowNulls { get; set; } = true;

    public string? DefaultExpression { get; set; }

    public string Type { get; set; }
    public Table Parent { get; internal set; } = null!;

    public bool IsPrimaryKey { get; internal set; }
    public bool IsAutoNumber { get; set; }

    /// <summary>
    ///     Computed (virtual) column expression. DDL emission for Oracle virtual
    ///     columns is not implemented yet — generating DDL for a column with
    ///     this set throws rather than silently creating a plain column.
    /// </summary>
    public string? ComputedExpression { get; set; }

    public bool ComputedColumnIsStored { get; set; }

    public string Name { get; }

    /// <summary>
    ///     For a column read from the catalog and sized in characters, its size in bytes
    ///     (<c>DATA_LENGTH</c>). The reader reported only that until it read <c>CHAR_LENGTH</c>, so a
    ///     model stating it matched, and still does; see <see cref="lengthsDiffer" />.
    /// </summary>
    internal int? StoredByteLength { get; init; }

    public string QuotedName => _preserveCase ? $"\"{Name}\"" : SchemaUtils.QuoteName(Name);

    public string RawType()
    {
        return Type.Split('(')[0].Trim();
    }

    public string Declaration()
    {
        if (ComputedExpression != null)
        {
            throw new NotSupportedException(
                "Computed (virtual) column DDL emission is not implemented for Oracle yet");
        }

        var parts = new List<string>();

        // In Oracle, the order is: DEFAULT, NULL/NOT NULL, IDENTITY, CHECK constraints
        if (DefaultExpression.IsNotEmpty())
        {
            parts.Add("DEFAULT " + DefaultExpression);
        }

        parts.Add(!IsPrimaryKey && AllowNulls ? "NULL" : "NOT NULL");

        if (IsAutoNumber)
        {
            parts.Add("GENERATED BY DEFAULT AS IDENTITY");
        }

        foreach (var check in ColumnChecks)
        {
            parts.Add(check.FullDeclaration());
        }

        return parts.Join(" ");
    }

    protected bool Equals(TableColumn other)
    {
        // Sizes are left out of the type-name comparison below, which is right for a NUMBER precision and
        // wrong for a VARCHAR2 length the model declared. See CharacterColumnLength: a widened VARCHAR2 used to
        // be invisible here, so an existing table kept the narrow column forever.
        if (lengthsDiffer(this, other))
        {
            return false;
        }

        return string.Equals(QuotedName, other.QuotedName, StringComparison.OrdinalIgnoreCase) &&
               string.Equals(StoredTypeName(Type), StoredTypeName(other.Type), StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    ///     Character lengths, compared on the stored spelling so that a length declared through
    ///     <c>CHARACTER VARYING</c> or <c>NATIONAL CHAR</c> counts like any other.
    /// </summary>
    /// <remarks>
    ///     A column sized in characters also matches a model that states its size in bytes. The reader
    ///     reported only <c>DATA_LENGTH</c> before it read <c>CHAR_LENGTH</c>, so such a model matched,
    ///     and reporting it now would <c>MODIFY</c> a settled column: that re-pads every stored
    ///     <c>CHAR</c> value, and <c>NVARCHAR2(2000)</c> against a model of <c>NVARCHAR2(4000)</c> is
    ///     ORA-00910 on every migration. Only a model spelled with a stored name is excused, because that
    ///     is the only kind that could match: <c>NCHAR VARYING(200)</c> never matched an
    ///     <c>NVARCHAR2</c>, so its <c>MODIFY</c> widened the column, and still does.
    /// </remarks>
    private static bool lengthsDiffer(TableColumn a, TableColumn b)
    {
        var aType = StoredSpelling(a.Type);
        var bType = StoredSpelling(b.Type);

        if (!CharacterColumnLength.Differ(aType, bType))
        {
            return false;
        }

        return !(statesByteLength(a, aType, b) || statesByteLength(b, bType, a));
    }

    private static readonly HashSet<string> StoredCharacterTypes = new(StringComparer.Ordinal)
    {
        "VARCHAR2", "CHAR", "NVARCHAR2", "NCHAR"
    };

    private static bool statesByteLength(TableColumn declared, string declaredSpelling, TableColumn column)
    {
        var open = declared.Type.IndexOf('(');
        if (open < 0 || !StoredCharacterTypes.Contains(collapse(declared.Type[..open])))
        {
            return false;
        }

        var length = CharacterColumnLength.TryParse(declaredSpelling);
        return length.HasValue && length == column.StoredByteLength;
    }

    private static readonly Regex Parenthesised = new(@"\([^)]*\)", RegexOptions.Compiled);
    private static readonly Regex Whitespace = new(@"\s+", RegexOptions.Compiled);

    /// <summary>
    ///     The name Oracle's catalog reports for a column declared as <paramref name="type" />, without
    ///     its sizes. Both sides of a comparison go through this, so a model may spell a type the way
    ///     Oracle rewrites it and still match the column Oracle created from it.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Every parenthesised part is removed, not only a trailing one: the catalog reports
    ///         <c>INTERVAL DAY(2) TO SECOND(6)</c> -- what a <see cref="TimeSpan" /> maps to -- and
    ///         <see cref="RawType" /> cut that name short, so the column never matched its own model.
    ///         Then the ANSI names Oracle rewrites are folded (<see cref="FoldAnsiName" />), and
    ///         <see cref="OracleProvider.ConvertSynonyms" /> is applied last, as before.
    ///     </para>
    ///     <para>
    ///         The TIMESTAMP family keeps the comparison it always had, cut at the first parenthesis, so
    ///         <c>TIMESTAMP(3) WITH TIME ZONE</c> still compares as <c>TIMESTAMP</c>. That leaves such a
    ///         model drifting against the column Oracle creates from it, but it also matches a plain
    ///         <c>TIMESTAMP</c> column today, and reporting that pair would <c>ALTER</c> a populated
    ///         column, which Oracle refuses (ORA-01439).
    ///     </para>
    /// </remarks>
    private static string StoredTypeName(string type)
    {
        var name = collapse(type).StartsWith("TIMESTAMP", StringComparison.Ordinal)
            ? collapse(type.Split('(')[0])
            : collapse(Parenthesised.Replace(type, " "));

        return OracleProvider.Instance.ConvertSynonyms(FoldAnsiName(name));
    }

    /// <summary>
    ///     The declared type with its name folded onto the one Oracle stores and its sizes kept:
    ///     <c>NATIONAL CHAR VARYING(20)</c> is <c>NVARCHAR2(20)</c>. This is the spelling character lengths
    ///     are compared in, which only recognises the stored names.
    /// </summary>
    private static string StoredSpelling(string type)
    {
        var open = type.IndexOf('(');
        return open < 0 ? FoldAnsiName(type) : FoldAnsiName(type[..open]) + type[open..];
    }

    /// <summary>
    ///     An ANSI type name folded onto the name <c>ALL_TAB_COLUMNS.DATA_TYPE</c> reports for it. Only
    ///     names that <see cref="OracleProvider.ConvertSynonyms" /> does not already map, or maps to a
    ///     sized <c>NUMBER</c> the catalog side can never produce: <c>DOUBLE PRECISION</c> is left to it,
    ///     because it has always read that as <c>BINARY_DOUBLE</c> and a model saying it matches such a
    ///     column.
    /// </summary>
    private static string FoldAnsiName(string name)
    {
        var collapsed = collapse(name);

        return collapsed switch
        {
            "NUMERIC" or "DECIMAL" or "DEC" or "INTEGER" or "INT" or "SMALLINT" => "NUMBER",
            "REAL" => "FLOAT",
            "VARCHAR" or "CHARACTER VARYING" or "CHAR VARYING" => "VARCHAR2",
            "CHARACTER" => "CHAR",
            "NATIONAL CHARACTER VARYING" or "NATIONAL CHAR VARYING" or "NCHAR VARYING" => "NVARCHAR2",
            "NATIONAL CHARACTER" or "NATIONAL CHAR" => "NCHAR",
            _ => collapsed
        };
    }

    private static string collapse(string value) => Whitespace.Replace(value, " ").Trim().ToUpperInvariant();

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (!obj.GetType().CanBeCastTo<TableColumn>())
        {
            return false;
        }

        return Equals((TableColumn)obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            // The same type name Equals compares, or two equal columns -- NUMERIC(13,4) and the
            // NUMBER(13,4) Oracle stores for it -- would hash apart.
            return (Name.ToUpperInvariant().GetHashCode() * 397) ^ StoredTypeName(Type).GetHashCode();
        }
    }

    public string ToDeclaration()
    {
        var declaration = Declaration();

        return declaration.IsEmpty()
            ? $"{QuotedName} {Type}"
            : $"{QuotedName} {Type} {declaration}";
    }

    public override string ToString()
    {
        return ToDeclaration();
    }

    public virtual string AlterColumnTypeSql(Table table, TableColumn changeActual)
    {
        // Two things were wrong here, and neither showed until character lengths started being compared
        // (see CharacterColumnLength) -- before that a column type delta was almost never detected at all.
        //
        // First, the side: the SQL Server and PostgreSQL twins both emit the receiver, which is the shape
        // the column is moving TO. This emitted changeActual, the shape it is moving FROM, so the
        // statement altered the column to what it already was. Both call sites in TableDelta pass the
        // target as the receiver, so reading the receiver is what they always meant.
        //
        // Second, the nullability: Oracle rejects a MODIFY that restates the nullability a column already
        // has -- ORA-01451 "column to be modified to NULL cannot be modified to NULL", and ORA-01442 for
        // the NOT NULL direction. So the clause is emitted only when it is actually changing, which is
        // what changeActual is for.
        var parts = new List<string> { QuotedName, Type };

        if (DefaultExpression.IsNotEmpty())
        {
            parts.Add("DEFAULT " + DefaultExpression);
        }

        var allowsNulls = !IsPrimaryKey && AllowNulls;
        if (allowsNulls != (!changeActual.IsPrimaryKey && changeActual.AllowNulls))
        {
            parts.Add(allowsNulls ? "NULL" : "NOT NULL");
        }

        return $"ALTER TABLE {table.Identifier} MODIFY {parts.Join(" ")}";
    }

    public string DropColumnSql(Table table)
    {
        return $"ALTER TABLE {table.Identifier} DROP COLUMN {QuotedName}";
    }

    public virtual bool CanAdd()
    {
        return AllowNulls || DefaultExpression.IsNotEmpty();
    }

    public virtual string AddColumnSql(Table parent)
    {
        return $"ALTER TABLE {parent.Identifier} ADD {ToDeclaration()}";
    }

    public virtual bool CanAlter(TableColumn actual)
    {
        return true;
    }
}

public abstract class ColumnCheck
{
    /// <summary>
    ///     The database name for the check. This can be null
    /// </summary>
    public string? Name { get; set; }

    public abstract string Declaration();

    public string FullDeclaration()
    {
        if (Name.IsEmpty())
        {
            return Declaration();
        }

        return $"CONSTRAINT {Name} {Declaration()}";
    }
}

public class SerialValue: ColumnCheck
{
    public override string Declaration()
    {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }
}
