using JasperFx.Core;
using JasperFx.Core.Reflection;
using Weasel.Core;

namespace Weasel.Oracle.Tables;

public class TableColumn: ITableColumn
{
    public TableColumn(string name, string type)
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentOutOfRangeException(nameof(name));
        }

        if (string.IsNullOrEmpty(type))
        {
            throw new ArgumentOutOfRangeException(nameof(type));
        }

        Name = name.ToLowerInvariant().Trim().Replace(' ', '_');
        Type = type.ToUpperInvariant();
    }

    public IList<ColumnCheck> ColumnChecks { get; } = new List<ColumnCheck>();

    public bool AllowNulls { get; set; } = true;

    public string? DefaultExpression { get; set; }

    public string Type { get; set; }
    public Table Parent { get; internal set; } = null!;

    public bool IsPrimaryKey { get; internal set; }
    public bool IsAutoNumber { get; set; }

    public string Name { get; }
    public string QuotedName => SchemaUtils.QuoteName(Name);

    public string RawType()
    {
        return Type.Split('(')[0].Trim();
    }

    public string Declaration()
    {
        var declaration = !IsPrimaryKey && AllowNulls ? "NULL" : "NOT NULL";
        if (IsAutoNumber)
        {
            declaration += " GENERATED BY DEFAULT AS IDENTITY";
        }

        if (DefaultExpression.IsNotEmpty())
        {
            declaration += " DEFAULT " + DefaultExpression;
        }

        return $"{declaration} {ColumnChecks.Select(x => x.FullDeclaration()).Join(" ")}".TrimEnd();
    }

    protected bool Equals(TableColumn other)
    {
        return string.Equals(QuotedName, other.QuotedName, StringComparison.OrdinalIgnoreCase) &&
               string.Equals(OracleProvider.Instance.ConvertSynonyms(RawType()),
                   OracleProvider.Instance.ConvertSynonyms(other.RawType()), StringComparison.OrdinalIgnoreCase);
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (!obj.GetType().CanBeCastTo<TableColumn>())
        {
            return false;
        }

        return Equals((TableColumn)obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (Name.ToUpperInvariant().GetHashCode() * 397) ^ Type.ToUpperInvariant().GetHashCode();
        }
    }

    public string ToDeclaration()
    {
        var declaration = Declaration();

        return declaration.IsEmpty()
            ? $"{QuotedName} {Type}"
            : $"{QuotedName} {Type} {declaration}";
    }

    public override string ToString()
    {
        return ToDeclaration();
    }

    public virtual string AlterColumnTypeSql(Table table, TableColumn changeActual)
    {
        return $"ALTER TABLE {table.Identifier} MODIFY {changeActual.ToDeclaration()}";
    }

    public string DropColumnSql(Table table)
    {
        return $"ALTER TABLE {table.Identifier} DROP COLUMN {QuotedName}";
    }

    public virtual bool CanAdd()
    {
        return AllowNulls || DefaultExpression.IsNotEmpty();
    }

    public virtual string AddColumnSql(Table parent)
    {
        return $"ALTER TABLE {parent.Identifier} ADD {ToDeclaration()}";
    }

    public virtual bool CanAlter(TableColumn actual)
    {
        return true;
    }
}

public abstract class ColumnCheck
{
    /// <summary>
    ///     The database name for the check. This can be null
    /// </summary>
    public string? Name { get; set; }

    public abstract string Declaration();

    public string FullDeclaration()
    {
        if (Name.IsEmpty())
        {
            return Declaration();
        }

        return $"CONSTRAINT {Name} {Declaration()}";
    }
}

public class SerialValue: ColumnCheck
{
    public override string Declaration()
    {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }
}
