using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using JasperFx.Core.Reflection;
using Weasel.Core.Sequences;

namespace Weasel.Core.Identity;

/// <summary>
///     <see cref="IIdentification{TDoc,TId}" /> for documents whose id is a <see cref="Guid" />
///     generated by <see cref="Guid.NewGuid" /> (random, non-sequential). Sibling of
///     <see cref="SequentialGuidIdentification{TDoc}" />; differs only in the generator used.
/// </summary>
public sealed class GuidIdentification<TDoc> : IIdentification<TDoc, Guid>
    where TDoc : notnull
{
    private readonly Func<TDoc, Guid> _getter;
    private readonly Action<TDoc, Guid>? _setter;

    [RequiresUnreferencedCode("Builds FEC-compiled accessor delegates over the id member via LambdaBuilder.")]
    public GuidIdentification(MemberInfo idMember)
    {
        _getter = LambdaBuilder.Getter<TDoc, Guid>(idMember);
        _setter = LambdaBuilder.Setter<TDoc, Guid>(idMember);
    }

    public Guid Identity(TDoc document) => _getter(document);

    public Guid AssignIfMissing(TDoc document, ISequenceSource sequences)
    {
        var current = _getter(document);
        if (current != Guid.Empty)
        {
            return current;
        }

        if (_setter is null)
        {
            return current;
        }

        var assigned = Guid.NewGuid();
        _setter(document, assigned);
        return assigned;
    }
}
