using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using JasperFx.Core.Reflection;
using Weasel.Core.Sequences;

namespace Weasel.Core.Identity;

/// <summary>
///     <see cref="IIdentification{TDoc,TId}" /> for documents whose id is an <see cref="int" />
///     generated by a Hi-Lo sequence. New ids come from the per-document-type <see cref="ISequence" />
///     resolved via <see cref="ISequenceSource.SequenceFor" />.
/// </summary>
public sealed class HiloIntIdentification<TDoc> : IIdentification<TDoc, int>
    where TDoc : notnull
{
    private readonly Func<TDoc, int> _getter;
    private readonly Action<TDoc, int>? _setter;
    private readonly Type _sequenceKey;

    /// <param name="idMember">The int-typed id member on <typeparamref name="TDoc" />.</param>
    /// <param name="sequenceKey">The type used as the cache key for <see cref="ISequenceSource.SequenceFor" />.</param>
    [RequiresUnreferencedCode("Builds FEC-compiled accessor delegates over the id member via LambdaBuilder.")]
    public HiloIntIdentification(MemberInfo idMember, Type sequenceKey)
    {
        _getter = LambdaBuilder.Getter<TDoc, int>(idMember);
        _setter = LambdaBuilder.Setter<TDoc, int>(idMember);
        _sequenceKey = sequenceKey;
    }

    public int Identity(TDoc document) => _getter(document);

    public int AssignIfMissing(TDoc document, ISequenceSource sequences)
    {
        var current = _getter(document);
        if (current > 0)
        {
            return current;
        }

        if (_setter is null) return current;

        var assigned = sequences.SequenceFor(_sequenceKey).NextInt();
        _setter(document, assigned);
        return assigned;
    }
}
