using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using JasperFx.Core.Reflection;
using Weasel.Core.Sequences;

namespace Weasel.Core.Identity;

/// <summary>
///     <see cref="IIdentification{TDoc,TId}" /> for documents whose id is a <see cref="long" />
///     generated by a Hi-Lo sequence. Sibling of <see cref="HiloIntIdentification{TDoc}" /> — differs
///     only in the <see cref="ISequence.NextLong" /> call vs <see cref="ISequence.NextInt" />.
/// </summary>
public sealed class HiloLongIdentification<TDoc> : IIdentification<TDoc, long>
    where TDoc : notnull
{
    private readonly Func<TDoc, long> _getter;
    private readonly Action<TDoc, long>? _setter;
    private readonly Type _sequenceKey;

    [RequiresUnreferencedCode("Builds FEC-compiled accessor delegates over the id member via LambdaBuilder.")]
    public HiloLongIdentification(MemberInfo idMember, Type sequenceKey)
    {
        _getter = LambdaBuilder.Getter<TDoc, long>(idMember);
        _setter = LambdaBuilder.Setter<TDoc, long>(idMember);
        _sequenceKey = sequenceKey;
    }

    public long Identity(TDoc document) => _getter(document);

    public long AssignIfMissing(TDoc document, ISequenceSource sequences)
    {
        var current = _getter(document);
        if (current > 0L)
        {
            return current;
        }

        if (_setter is null) return current;

        var assigned = sequences.SequenceFor(_sequenceKey).NextLong();
        _setter(document, assigned);
        return assigned;
    }
}
